package io.github.docmorphic.cmuxapp

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.*
import org.junit.Test
import java.io.File
import java.util.Base64

/** Public fixed test keys, never actual installation credentials. Apple ciphertext
 * and canonical bytes were generated by the pinned upstream production Swift code. */
class PhonePushCryptoTest {
    private fun fixtures(): List<JSONObject> {
        val values = JSONArray(javaClass.getResource("/push/apple-hpke-v2.json")!!.readText())
        return (0 until values.length()).map(values::getJSONObject)
    }
    private fun bytes(value: JSONObject, key: String) = Base64.getDecoder().decode(value.getString(key))
    private fun envelope(value: JSONObject) = PhonePushEnvelope.parse(value.getJSONObject("envelope"))
    private fun open(value: JSONObject, envelope: PhonePushEnvelope = envelope(value), expected: PhonePushTuple = envelope(value).tuple,
        sender: ByteArray = bytes(value, "senderPublicKeyBase64"), recipient: ByteArray = bytes(value, "recipientPrivateKeyBase64")) =
        PhonePushCrypto.decrypt(envelope, expected, "test-phone", "test-recipient-key", "test-sender-key", sender, recipient)

    @Test fun appleEnvelopesDecryptWithIdenticalCanonicalTupleBytes() {
        for (fixture in fixtures()) {
            val value = envelope(fixture)
            assertArrayEquals(bytes(fixture, "canonicalTupleBase64"), value.tuple.canonical())
            assertArrayEquals(bytes(fixture, "plaintextBase64"), open(fixture))
            assertEquals(value, PhonePushEnvelope.parse(MobileJson.objectValue(value.wire().toString(), requireComplete = true)))
        }
    }

    @Test fun androidEnvelopesRoundTripAndCanBeCheckedByApple() {
        val generated = JSONArray()
        for ((index, fixture) in fixtures().withIndex()) {
            val tuple = envelope(fixture).tuple
            val plaintext = "Generated Android push fixture λ 中 $index".toByteArray()
            fun seal() = PhonePushCrypto.encrypt(plaintext, tuple, "test-recipient-key", "test-sender-key",
                bytes(fixture, "recipientPublicKeyBase64"), bytes(fixture, "senderPrivateKeyBase64"))
            val value = seal()
            assertArrayEquals(plaintext, open(fixture, value))
            assertNotEquals(value.encapsulatedKey, seal().encapsulatedKey)
            generated.put(value.wire())
        }
        System.getenv("CMUX_PUSH_CROSS_OUTPUT")?.let { File(it).writeText(generated.toString(2)) }
    }

    @Test fun everyTupleFieldAndRecipientSenderBindingAreEnforced() {
        val fixture = fixtures().first(); val value = envelope(fixture); val t = value.tuple
        for (changed in listOf(t.copy(accountID = "other"), t.copy(teamID = "other"), t.copy(iosBuildID = "other"),
            t.copy(iosInstallationID = "other"), t.copy(macDeviceID = "other"), t.copy(macInstanceTag = "other"), t.copy(macBuildID = "other"))) {
            assertThrows(Exception::class.java) { open(fixture, value, changed) }
            // Even a caller accidentally trusting altered metadata cannot authenticate it.
            assertThrows(Exception::class.java) { open(fixture, value.copy(tuple = changed), changed) }
        }
        for (changed in listOf(value.copy(installationID = "other"), value.copy(keyID = "other"),
            value.copy(senderKeyID = "other"), value.copy(version = 1), value.copy(version = 3))) {
            assertThrows(Exception::class.java) { open(fixture, changed) }
        }
        assertThrows(Exception::class.java) { open(fixture, sender = ByteArray(32) { 7 }) }
        assertThrows(Exception::class.java) { open(fixture, recipient = ByteArray(32) { 8 }) }
        assertThrows(Exception::class.java) { open(fixture, sender = ByteArray(32)) }
    }

    @Test fun corruptedCiphertextAndEncapsulationNeverYieldPlaintext() {
        val fixture = fixtures().first(); val value = envelope(fixture)
        for (field in listOf("encapsulatedKey", "ciphertext")) {
            val original = Base64.getDecoder().decode(if (field == "ciphertext") value.ciphertext else value.encapsulatedKey)
            for (offset in listOf(0, original.lastIndex)) {
                val changed = original.copyOf().also { it[offset] = (it[offset].toInt() xor 1).toByte() }
                val text = Base64.getEncoder().encodeToString(changed)
                assertThrows(Exception::class.java) {
                    open(fixture, if (field == "ciphertext") value.copy(ciphertext = text) else value.copy(encapsulatedKey = text))
                }
            }
        }
    }

    @Test fun malformedAndOversizedWireValuesAreRejectedBeforeCrypto() {
        val fixture = fixtures().first(); val value = envelope(fixture)
        for (bad in listOf("!", "", "AA==", "A".repeat(22000))) {
            assertThrows(Exception::class.java) { open(fixture, value.copy(ciphertext = bad)) }
            assertThrows(Exception::class.java) { open(fixture, value.copy(encapsulatedKey = bad)) }
        }
        for (bad in listOf("2", 2.5, 1, JSONObject.NULL))
            assertThrows(Exception::class.java) { PhonePushEnvelope.parse(value.wire().put("version", bad)) }
        assertThrows(Exception::class.java) { PhonePushEnvelope.parse(value.wire().put("keyID", 1)) }
        assertThrows(Exception::class.java) { PhonePushEnvelope.parse(value.wire().put("installationID", "")) }
        assertThrows(Exception::class.java) { PhonePushEnvelope.parse(value.wire().put("ciphertext", "A".repeat(22000))) }
        assertThrows(Exception::class.java) { open(fixture, recipient = ByteArray(31)) }
        assertThrows(Exception::class.java) {
            PhonePushCrypto.encrypt(ByteArray(16369), value.tuple, value.keyID, value.senderKeyID,
                bytes(fixture, "recipientPublicKeyBase64"), bytes(fixture, "senderPrivateKeyBase64"))
        }
    }
}
